/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1;

import codigo_fs.Array;
import codigo_fs.Objeto;
import codigo_gdato.FileArray;
import codigo_gdato.item;
import codigo_gdato.tupla;
import g_datos.lexico_d;
import g_datos.sintactico_d;
import g_gxml.lexico_g;
import g_gxml.sintactico_g;
import java.io.BufferedReader;
import java.io.StringReader;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.LinkedList;
import static proyecto1.Reconize.getContenido;
import ts.Simbolo;

/**
 *
 * @author Pamela Palacios
 */
public class gdato extends javax.swing.JFrame {

    /**
     * Creates new form gdato
     */
    public gdato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FileArray raiz = null;        
        try
        {
            lexico_d le = new lexico_d(new BufferedReader( new StringReader(jTextArea1.getText())));            
            sintactico_d sintactico=new sintactico_d(le);
            sintactico.parse();            
            raiz =sintactico.raiz;
            //e.Adding(le.e);
            //e.Adding(sintactico.e);
            if(raiz!=null)
            {
                int i=0;
                LinkedList<tupla> tuplas=raiz.tuplas;
                for(tupla s:tuplas)
                {
                    System.out.println("****************"+i+"****************");
                    Enumeration e = s.items.keys();
                        Object clave;
                        item valor;
                        while( e.hasMoreElements() ){
                          clave = e.nextElement();
                          valor = (item)s.items.get( clave );
                          System.out.println("clave: "+valor.clave+"|valor: "+valor.valor.toString());
                        }
                        i++;
                }
            }/*else
            {
                this.txtError.setText("entrada incorrecta");
            }*/
        }catch(Exception ex){

                System.out.println("ex: "+ex.getMessage());
                //e.AddError("entrada incorrecta", 0, 0, var.archivo, "EJECUCION");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public Array getArrayFromFile(FileArray raiz)
    {
        LinkedList<Simbolo>valores=new LinkedList();
        
        LinkedList<tupla> tuplas=raiz.tuplas;
        for(tupla s:tuplas)
        {
            Hashtable vv=new Hashtable();
            Enumeration e = s.items.keys();
            Object clave;
            item valor;
            while( e.hasMoreElements() ){
                clave = e.nextElement();
                valor = (item)s.items.get( clave );                
                if(vv.containsKey(clave))
                {
                    //e.AddError("el objeto tiene una clave repetida", linea, columna, archivo, "SEMANTICO");
                    return null;
                }else
                {
                    Simbolo pp=new Simbolo(var.tipo_cadena,valor.valor.toString());
                    //vv.put(clave,new item(clave,pp,linea,columna,archivo));
                } 
            }
            valores.add(new Simbolo(var.tipo_objeto,new Objeto(vv)));
                       
        }
        return new Array(valores);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gdato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gdato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gdato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gdato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gdato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
