
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package g_fs;

import java.io.*;
import java_cup.runtime.*;
import java.util.LinkedList;
import errors.mng_error;
import proyecto1.var;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class sintactico_fs extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return symbl.class;
}

  /** Default constructor. */
  @Deprecated
  public sintactico_fs() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public sintactico_fs(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public sintactico_fs(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\002\000\002\002\004\000\002\002\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\004\000\004\005\005\001\002\000\004\002\006\001" +
    "\002\000\004\002\000\001\002\000\004\002\001\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\004\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$sintactico_fs$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$sintactico_fs$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$sintactico_fs$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



public mng_error e = new mng_error();
public void syntax_error(Symbol s){
        e.AddError("No se esperaba "+s.value,(s.left+1),(s.right+1),var.archivo,"SINTACTICO"); 
}
             
public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
       e.AddError("No se esperaba "+s.value,(s.left+1),(s.right+1),var.archivo,"SINTACTICO"); ;
}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$sintactico_fs$actions {


      

  private final sintactico_fs parser;

  /** Constructor */
  CUP$sintactico_fs$actions(sintactico_fs parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$sintactico_fs$do_action_part00000000(
    int                        CUP$sintactico_fs$act_num,
    java_cup.runtime.lr_parser CUP$sintactico_fs$parser,
    java.util.Stack            CUP$sintactico_fs$stack,
    int                        CUP$sintactico_fs$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$sintactico_fs$result;

      /* select the action based on the action number */
      switch (CUP$sintactico_fs$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= S EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$sintactico_fs$stack.elementAt(CUP$sintactico_fs$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$sintactico_fs$stack.elementAt(CUP$sintactico_fs$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$sintactico_fs$stack.elementAt(CUP$sintactico_fs$top-1)).value;
		RESULT = start_val;
              CUP$sintactico_fs$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$sintactico_fs$stack.elementAt(CUP$sintactico_fs$top-1)), ((java_cup.runtime.Symbol)CUP$sintactico_fs$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$sintactico_fs$parser.done_parsing();
          return CUP$sintactico_fs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // S ::= er_id 
            {
              String RESULT =null;
		
                System.out.println("aceptada");
                //raiz=n1;
            
              CUP$sintactico_fs$result = parser.getSymbolFactory().newSymbol("S",0, ((java_cup.runtime.Symbol)CUP$sintactico_fs$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico_fs$stack.peek()), RESULT);
            }
          return CUP$sintactico_fs$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$sintactico_fs$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$sintactico_fs$do_action(
    int                        CUP$sintactico_fs$act_num,
    java_cup.runtime.lr_parser CUP$sintactico_fs$parser,
    java.util.Stack            CUP$sintactico_fs$stack,
    int                        CUP$sintactico_fs$top)
    throws java.lang.Exception
    {
              return CUP$sintactico_fs$do_action_part00000000(
                               CUP$sintactico_fs$act_num,
                               CUP$sintactico_fs$parser,
                               CUP$sintactico_fs$stack,
                               CUP$sintactico_fs$top);
    }
}

}
