
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package g_fs;

/** CUP generated class containing symbol constants. */
public class symbl {
  /* terminals */
  public static final int mul = 16;
  public static final int menos = 15;
  public static final int menor = 13;
  public static final int funcion = 48;
  public static final int area = 73;
  public static final int varvar = 30;
  public static final int a_por = 35;
  public static final int pto = 33;
  public static final int corc = 39;
  public static final int musica = 68;
  public static final int pote = 18;
  public static final int cora = 38;
  public static final int nulo = 3;
  public static final int reduce = 58;
  public static final int controln = 72;
  public static final int ptocoma = 24;
  public static final int importar = 40;
  public static final int descendente = 49;
  public static final int imagen = 69;
  public static final int selecciona = 45;
  public static final int boton = 70;
  public static final int mas = 14;
  public static final int map = 56;
  public static final int imprimir = 29;
  public static final int ObtenerPorId = 64;
  public static final int op_and = 27;
  public static final int detener = 43;
  public static final int sino = 42;
  public static final int todos = 59;
  public static final int dif = 11;
  public static final int ques = 25;
  public static final int maximo = 53;
  public static final int caso = 46;
  public static final int filter = 55;
  public static final int menori = 10;
  public static final int mayori = 9;
  public static final int alguno = 60;
  public static final int er_entero = 80;
  public static final int is = 32;
  public static final int aumen = 7;
  public static final int video = 67;
  public static final int er_id = 77;
  public static final int a_div = 37;
  public static final int op_or = 26;
  public static final int invertir = 52;
  public static final int a_mas = 34;
  public static final int id = 2;
  public static final int cerrar = 65;
  public static final int er_decimal = 78;
  public static final int dosptos = 23;
  public static final int ObtenerPorEtiqueta = 62;
  public static final int leerGxml = 61;
  public static final int minimo = 54;
  public static final int a_menos = 36;
  public static final int divis = 17;
  public static final int ascendente = 50;
  public static final int retornar = 44;
  public static final int mayor = 12;
  public static final int ObtenerPorNombre = 63;
  public static final int texto = 75;
  public static final int op_not = 28;
  public static final int clic = 66;
  public static final int EOF = 0;
  public static final int decre = 6;
  public static final int falso = 5;
  public static final int verdadero = 4;
  public static final int llavc = 20;
  public static final int error = 1;
  public static final int llava = 19;
  public static final int buscar = 57;
  public static final int si = 41;
  public static final int er_cadena = 79;
  public static final int caja = 74;
  public static final int defecto = 47;
  public static final int parc = 22;
  public static final int para = 21;
  public static final int contenedor = 76;
  public static final int coma = 31;
  public static final int igual = 8;
  public static final int crearArrFile = 51;
  public static final int desple = 71;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "id",
  "nulo",
  "verdadero",
  "falso",
  "decre",
  "aumen",
  "igual",
  "mayori",
  "menori",
  "dif",
  "mayor",
  "menor",
  "mas",
  "menos",
  "mul",
  "divis",
  "pote",
  "llava",
  "llavc",
  "para",
  "parc",
  "dosptos",
  "ptocoma",
  "ques",
  "op_or",
  "op_and",
  "op_not",
  "imprimir",
  "varvar",
  "coma",
  "is",
  "pto",
  "a_mas",
  "a_por",
  "a_menos",
  "a_div",
  "cora",
  "corc",
  "importar",
  "si",
  "sino",
  "detener",
  "retornar",
  "selecciona",
  "caso",
  "defecto",
  "funcion",
  "descendente",
  "ascendente",
  "crearArrFile",
  "invertir",
  "maximo",
  "minimo",
  "filter",
  "map",
  "buscar",
  "reduce",
  "todos",
  "alguno",
  "leerGxml",
  "ObtenerPorEtiqueta",
  "ObtenerPorNombre",
  "ObtenerPorId",
  "cerrar",
  "clic",
  "video",
  "musica",
  "imagen",
  "boton",
  "desple",
  "controln",
  "area",
  "caja",
  "texto",
  "contenedor",
  "er_id",
  "er_decimal",
  "er_cadena",
  "er_entero"
  };
}

