
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package g_fs;

/** CUP generated class containing symbol constants. */
public class symbl {
  /* terminals */
  public static final int mul = 15;
  public static final int menos = 14;
  public static final int menor = 12;
  public static final int funcion = 47;
  public static final int area = 72;
  public static final int varvar = 29;
  public static final int a_por = 34;
  public static final int pto = 32;
  public static final int corc = 38;
  public static final int musica = 67;
  public static final int pote = 17;
  public static final int cora = 37;
  public static final int nulo = 2;
  public static final int reduce = 57;
  public static final int controln = 71;
  public static final int ptocoma = 23;
  public static final int importar = 39;
  public static final int descendente = 48;
  public static final int imagen = 68;
  public static final int selecciona = 44;
  public static final int boton = 69;
  public static final int mas = 13;
  public static final int map = 55;
  public static final int imprimir = 28;
  public static final int ObtenerPorId = 63;
  public static final int op_and = 26;
  public static final int detener = 42;
  public static final int sino = 41;
  public static final int todos = 58;
  public static final int dif = 10;
  public static final int ques = 24;
  public static final int maximo = 52;
  public static final int caso = 45;
  public static final int filter = 54;
  public static final int menori = 9;
  public static final int mayori = 8;
  public static final int alguno = 59;
  public static final int er_entero = 80;
  public static final int is = 31;
  public static final int aumen = 6;
  public static final int video = 66;
  public static final int er_id = 77;
  public static final int a_div = 36;
  public static final int op_or = 25;
  public static final int invertir = 51;
  public static final int a_mas = 33;
  public static final int cerrar = 64;
  public static final int er_decimal = 78;
  public static final int dosptos = 22;
  public static final int ObtenerPorEtiqueta = 61;
  public static final int leerGxml = 60;
  public static final int minimo = 53;
  public static final int a_menos = 35;
  public static final int divis = 16;
  public static final int cargar = 76;
  public static final int ascendente = 49;
  public static final int retornar = 43;
  public static final int mayor = 11;
  public static final int ObtenerPorNombre = 62;
  public static final int texto = 74;
  public static final int op_not = 27;
  public static final int clic = 65;
  public static final int EOF = 0;
  public static final int decre = 5;
  public static final int falso = 4;
  public static final int verdadero = 3;
  public static final int llavc = 19;
  public static final int error = 1;
  public static final int llava = 18;
  public static final int buscar = 56;
  public static final int si = 40;
  public static final int er_cadena = 79;
  public static final int caja = 73;
  public static final int defecto = 46;
  public static final int parc = 21;
  public static final int para = 20;
  public static final int contenedor = 75;
  public static final int coma = 30;
  public static final int igual = 7;
  public static final int crearArrFile = 50;
  public static final int desple = 70;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "nulo",
  "verdadero",
  "falso",
  "decre",
  "aumen",
  "igual",
  "mayori",
  "menori",
  "dif",
  "mayor",
  "menor",
  "mas",
  "menos",
  "mul",
  "divis",
  "pote",
  "llava",
  "llavc",
  "para",
  "parc",
  "dosptos",
  "ptocoma",
  "ques",
  "op_or",
  "op_and",
  "op_not",
  "imprimir",
  "varvar",
  "coma",
  "is",
  "pto",
  "a_mas",
  "a_por",
  "a_menos",
  "a_div",
  "cora",
  "corc",
  "importar",
  "si",
  "sino",
  "detener",
  "retornar",
  "selecciona",
  "caso",
  "defecto",
  "funcion",
  "descendente",
  "ascendente",
  "crearArrFile",
  "invertir",
  "maximo",
  "minimo",
  "filter",
  "map",
  "buscar",
  "reduce",
  "todos",
  "alguno",
  "leerGxml",
  "ObtenerPorEtiqueta",
  "ObtenerPorNombre",
  "ObtenerPorId",
  "cerrar",
  "clic",
  "video",
  "musica",
  "imagen",
  "boton",
  "desple",
  "controln",
  "area",
  "caja",
  "texto",
  "contenedor",
  "cargar",
  "er_id",
  "er_decimal",
  "er_cadena",
  "er_entero"
  };
}

