
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package color_gxml;

/** CUP generated class containing symbol constants. */
public class g_simb {
  /* terminals */
  public static final int error = 1;
  public static final int menor = 2;
  public static final int EOF = 0;
  public static final int reservada = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "menor",
  "reservada"
  };
}

