
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package g_datos;

/** CUP generated class containing symbol constants. */
public class simbolo {
  /* terminals */
  public static final int error = 1;
  public static final int er_id = 3;
  public static final int er_entero = 4;
  public static final int EOF = 0;
  public static final int id = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "id",
  "er_id",
  "er_entero"
  };
}

