
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package g_datos;

/** CUP generated class containing symbol constants. */
public class simbolo {
  /* terminals */
  public static final int f_lista = 11;
  public static final int er_cadena = 3;
  public static final int i_prin = 9;
  public static final int er_decimal = 5;
  public static final int er_id = 4;
  public static final int f_prin = 10;
  public static final int slash = 7;
  public static final int is = 14;
  public static final int EOF = 0;
  public static final int er_entero = 6;
  public static final int menor = 2;
  public static final int i_lista = 12;
  public static final int error = 1;
  public static final int tipo = 13;
  public static final int mayor = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "menor",
  "er_cadena",
  "er_id",
  "er_decimal",
  "er_entero",
  "slash",
  "mayor",
  "i_prin",
  "f_prin",
  "f_lista",
  "i_lista",
  "tipo",
  "is"
  };
}

